const mongoose = require('mongoose');

const aideSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      required: true,
      enum: ['alimentaire', 'medication', 'aide_specifique']
    },
    quantity: {
      type: Number,
      required: true,
      min: 1
    },
    aidDate: {
      type: Date,
      default: Date.now,
      required: true
    },
    // Optional linkage when an aid record is generated by a public donation flow.
    publicPost: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'PublicPost',
      default: null,
      index: true
    },
    donationSessionId: {
      type: String,
      trim: true,
      maxlength: 120,
      select: false
    },
    observations: {
      type: String,
      trim: true,
      maxlength: 2000,
      default: ''
    },
    famille: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Famille',
      required: true,
      index: true
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Utilisateur',
      required: true
    }
  },
  {
    timestamps: true,
    toJSON: {
      transform: (_, ret) => {
        delete ret.__v;
        return ret;
      }
    }
  }
);

aideSchema.index({ type: 1 });
aideSchema.index({ aidDate: -1 });
aideSchema.index({ donationSessionId: 1 }, { unique: true, sparse: true });

module.exports = mongoose.model('Aide', aideSchema);
